# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [1]:
import numpy as np
# formula = weight / (height**2) * 730
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]

# OUTPUT: [16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
# 22.06222222]


In [5]:
###ANSWER###
import numpy as np
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]

height_arr = np.array(height)
weight_arr = np.array(weight)

def bmi_arr(hght, wght):
    bmi = wght / (hght**2) * 730
    return bmi

print(bmi_arr(height_arr, weight_arr))
    


[16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
 22.06222222]


### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [2]:
"""
Example Result
array([[14.21633515,  7.98846653,  9.64140715],
       [ 6.30982234,  9.96414331,  8.43153688],
       [14.73102068, 11.76072894, 14.23356121]])
"""
# def makeMatrix(low,high,shape,data_type = float): -- Example
#     pass

'\nExample Result\narray([[14.21633515,  7.98846653,  9.64140715],\n       [ 6.30982234,  9.96414331,  8.43153688],\n       [14.73102068, 11.76072894, 14.23356121]])\n'

In [20]:
###ANSWER###
import numpy as np

def makeMatrix(low,high,rows = 1, cols = 1,data_type = float): 
    matrix = np.random.uniform(low, high, (rows, cols))
    matrix2 = matrix.astype(data_type)
    return matrix2

print(makeMatrix(0,20))
print('\n')
print(makeMatrix(1,2,3,3))
print('\n')
print(makeMatrix(0,10,4,2,int))

[[0.67439961]]


[[1.81572199 1.90729767 1.52264388]
 [1.01294901 1.45623229 1.59705087]
 [1.84233836 1.22572083 1.78499959]]


[[4 1]
 [8 7]
 [2 0]
 [6 5]]


### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [ ]:
import csv
import numpy as np

#Test to make sure you have the correct data



In [23]:
"""
Example Result - Not the actual result
Boston 18 had more SLG in 2018
[0.404 0.443 0.392 0.403 0.482 0.424 0.402 0.459 0.429 0.354 0.387 0.333
 0.539 0.243 0.262 0.354 0.342 0.339 0.328 0.306 0.222 0.2   1.   ]
"""

FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray



In [102]:
###ANSWER###

def load_data(filename, d = ','):
    data = np.genfromtxt(filename, delimiter = d, skip_header = 1,
                        usecols = np.arange(0,24), invalid_raise = False,
                        names = FIELDS, dtype = DATATYPES)
    return data

bs2017 = load_data("../files/redsox_2017_hitting.txt")
bs2018 = load_data("../files/redsox_2018_hitting.txt")

names = bs2017['Name'], bs2018['Name']

#print(names)
# print('\n')

bs2017_slg = bs2017["SLG"]
bs2018_slg = bs2018["SLG"]
bs2017_names = bs2017['Name']
bs2018_names = bs2018['Name']
new_names_2017 = []
new_names_2018 = []

def decoded_bs(bs_names, new_names):
    for name in range(len(bs_names)):
        new_names.append(bs_names[name].decode('utf-8'))
    return new_names
    
new_names_2017 = decoded_bs(bs2017_names, new_names_2017)
# print(new_names_2017)
# print('\n')
new_names_2018 = decoded_bs(bs2017_names, new_names_2018)
# print(new_names_2018)
# print('\n')

def zipped_values(names, slg):
    zipped_final = list(zip(names, slg))
    return zipped_final

zipped_2017 = zipped_values(new_names_2017, bs2017_slg)
# print(zipped_2017)
# print('\n')
zipped_2018 = zipped_values(new_names_2018, bs2018_slg)
# print(zipped_2018)
# print('\n')

def sorted_slg(zipped_values):
    fin_sorted_slg = sorted(zipped_values, key = lambda x: x[0], reverse = False )
    return fin_sorted_slg

sorted_2017 = sorted_slg(zipped_2017)
print(f'The sorted list for the 2017 SLG is:\n{sorted_2017}')
print('\n')
sorted_2018 = sorted_slg(zipped_2018)
print(f'The sorted list for the 2018 SLG is:\n{sorted_2018}')
print('\n')

def slg_difference_player(year_1, year_2):
    slg_diff = []
    for player1 in year_1:
        for player2 in year_2:
            if player1[0] == player2[0]:
                new_player = player1[0], player2[1]-player1[1]
                slg_diff.append(new_player)
    return slg_diff
      
slg_diff_plyr = slg_difference_player(sorted_2017, sorted_2018)
print('\n')
print(f'The difference of each player SLG (year 2 - year 1) is:\n{slg_diff_plyr}')
        
class slg_total():
    def __init__(self, year_1, year_2):
        self.year_1 = year_1
        self.year_2 = year_2
    
    def slg_sum(year_1, year_2 = []):
        slg_sum_l = []
        for player1 in year_1:
            slg_sum_l.append(player1[1])
        for player2 in year_2:
            slg_sum_l.append(player2[1])
        return sum(slg_sum_l)
    
    def slg_diff(year_1, year_2):
        slg_diff_l1 = []
        slg_diff_l2 = []
        for player1 in year_1:
            slg_diff_l1.append(player1[1])
        for player2 in year_2:
            slg_diff_l2.append(player2[1])
        slg_diff_tot = sum(slg_diff_l2) - sum(slg_diff_l1)
        return slg_diff_tot

print('\n\n')
slg_sum_2017 = slg_total.slg_sum(sorted_2017)
print(f'The sum of SLG for 2017 is: {slg_sum_2017}')
slg_sum_2018 = slg_total.slg_sum(sorted_2018)
print(f'The sum of SLG for 2018 is: {slg_sum_2018}')
slg_sum_tot = slg_total.slg_sum(sorted_2017, sorted_2018)
print(f'The sum of SLG for both years is: {slg_sum_tot}')
print('\n')
slg_diff_tot = slg_total.slg_diff(sorted_2017, sorted_2018)
print(f'The difference (year 2 - year 1) of SLG for both years is: {slg_diff_tot}')
        
    

The sorted list for the 2017 SLG is:
[('Andrew Benintendi', 0.424), ('Blake Swihart', 0.2), ('Brock Holt', 0.243), ("Chase d'Arnaud", 1.0), ('Chris Young', 0.387), ('Christian Vazquez', 0.404), ('Deven Marrero', 0.333), ('Dustin Pedroia', 0.392), ('Eduardo Nunez', 0.539), ('Hanley Ramirez', 0.429), ('Jackie Bradley Jr.', 0.402), ('Josh Rutledge', 0.262), ('Marco Hernandez', 0.328), ('Mitch Moreland', 0.443), ('Mookie Betts', 0.459), ('Pablo Sandoval', 0.354), ('Rafael Devers', 0.482), ('Rajai Davis', 0.306), ('Sam Travis', 0.342), ('Sandy Leon', 0.354), ('Steve Selsky', 0.222), ('Tzu-Wei Lin', 0.339), ('Xander Bogaerts', 0.403)]


The sorted list for the 2018 SLG is:
[('Andrew Benintendi', 0.465), ('Brock Holt', 0.507), ('Chris Young', 0.283), ('Christian Vazquez', 0.279), ('Deven Marrero', 0.328), ('Dustin Pedroia', 0.388), ('Eduardo Nunez', 0.395), ('Hanley Ramirez', 0.629), ('Jackie Bradley Jr.', 0.403), ('Josh Rutledge', 0.311), ('Marco Hernandez', 0.091), ('Mitch Moreland', 0.433)